In [1]:
import fastf1
import pandas as pd

In [2]:
import os

os.makedirs('./f1_cache', exist_ok=True)
fastf1.Cache.enable_cache('./f1_cache')

In [3]:
years = [2020,2021,2022,2023,2024]
schedules=[]
for year in years:
    schedule = fastf1.get_event_schedule(year)
    schedules.append(schedule)

schedules=pd.concat(schedules)
schedules

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Spain,Barcelona,FORMULA 1 PRE-SEASON TESTING 2020,2020-02-21,Pre-Season Test 1,testing,Practice 1,2020-02-19 09:00:00+01:00,2020-02-19 08:00:00,...,Practice 3,2020-02-21 09:00:00+01:00,2020-02-21 08:00:00,None,NaT,NaT,None,NaT,NaT,False
1,0,Spain,Barcelona,FORMULA 1 PRE-SEASON TESTING 2020,2020-02-28,Pre-Season Test 2,testing,Practice 1,2020-02-26 09:00:00+01:00,2020-02-26 08:00:00,...,Practice 3,2020-02-28 09:00:00+01:00,2020-02-28 08:00:00,None,NaT,NaT,None,NaT,NaT,False
2,1,Austria,Spielberg,FORMULA 1 ROLEX GROSSER PREIS VON ÖSTERREICH 2020,2020-07-05,Austrian Grand Prix,conventional,Practice 1,2020-07-03 11:00:00+02:00,2020-07-03 09:00:00,...,Practice 3,2020-07-04 12:00:00+02:00,2020-07-04 10:00:00,Qualifying,2020-07-04 15:00:00+02:00,2020-07-04 13:00:00,Race,2020-07-05 15:10:00+02:00,2020-07-05 13:10:00,True
3,2,Austria,Spielberg,FORMULA 1 PIRELLI GROSSER PREIS DER STEIERMARK...,2020-07-12,Styrian Grand Prix,conventional,Practice 1,2020-07-10 11:00:00+02:00,2020-07-10 09:00:00,...,Practice 3,2020-07-11 12:00:00+02:00,2020-07-11 10:00:00,Qualifying,2020-07-11 15:00:00+02:00,2020-07-11 13:00:00,Race,2020-07-12 15:10:00+02:00,2020-07-12 13:10:00,True
4,3,Hungary,Budapest,FORMULA 1 ARAMCO MAGYAR NAGYDÍJ 2020,2020-07-19,Hungarian Grand Prix,conventional,Practice 1,2020-07-17 11:00:00+02:00,2020-07-17 09:00:00,...,Practice 3,2020-07-18 12:00:00+02:00,2020-07-18 10:00:00,Qualifying,2020-07-18 15:00:00+02:00,2020-07-18 13:00:00,Race,2020-07-19 15:10:00+02:00,2020-07-19 13:10:00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,20,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2024,2024-10-27,Mexico City Grand Prix,conventional,Practice 1,2024-10-25 12:30:00-06:00,2024-10-25 18:30:00,...,Practice 3,2024-10-26 11:30:00-06:00,2024-10-26 17:30:00,Qualifying,2024-10-26 15:00:00-06:00,2024-10-26 21:00:00,Race,2024-10-27 14:00:00-06:00,2024-10-27 20:00:00,True
21,21,Brazil,São Paulo,FORMULA 1 LENOVO GRANDE PRÊMIO DE SÃO PAULO 2024,2024-11-03,São Paulo Grand Prix,sprint_qualifying,Practice 1,2024-11-01 11:30:00-03:00,2024-11-01 14:30:00,...,Sprint,2024-11-02 11:00:00-03:00,2024-11-02 14:00:00,Qualifying,2024-11-03 07:30:00-03:00,2024-11-03 10:30:00,Race,2024-11-03 12:30:00-03:00,2024-11-03 15:30:00,True
22,22,United States,Las Vegas,FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX...,2024-11-23,Las Vegas Grand Prix,conventional,Practice 1,2024-11-21 18:30:00-08:00,2024-11-22 02:30:00,...,Practice 3,2024-11-22 18:30:00-08:00,2024-11-23 02:30:00,Qualifying,2024-11-22 22:00:00-08:00,2024-11-23 06:00:00,Race,2024-11-23 22:00:00-08:00,2024-11-24 06:00:00,True
23,23,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2024,2024-12-01,Qatar Grand Prix,sprint_qualifying,Practice 1,2024-11-29 16:30:00+03:00,2024-11-29 13:30:00,...,Sprint,2024-11-30 17:00:00+03:00,2024-11-30 14:00:00,Qualifying,2024-11-30 21:00:00+03:00,2024-11-30 18:00:00,Race,2024-12-01 19:00:00+03:00,2024-12-01 16:00:00,True
24,24,United Arab Emirates,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2024-12-08,Abu Dhabi Grand Prix,conventional,Practice 1,2024-12-06 13:30:00+04:00,2024-12-06 09:30:00,...,Practice 3,2024-12-07 14:30:00+04:00,2024-12-07 10:30:00,Qualifying,2024-12-07 18:00:00+04:00,2024-12-07 14:00:00,Race,2024-12-08 17:00:00+04:00,2024-12-08 13:00:00,True

In [4]:
races = schedules[schedules['EventFormat'] == 'conventional']
races

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
2,1,Austria,Spielberg,FORMULA 1 ROLEX GROSSER PREIS VON ÖSTERREICH 2020,2020-07-05,Austrian Grand Prix,conventional,Practice 1,2020-07-03 11:00:00+02:00,2020-07-03 09:00:00,...,Practice 3,2020-07-04 12:00:00+02:00,2020-07-04 10:00:00,Qualifying,2020-07-04 15:00:00+02:00,2020-07-04 13:00:00,Race,2020-07-05 15:10:00+02:00,2020-07-05 13:10:00,True
3,2,Austria,Spielberg,FORMULA 1 PIRELLI GROSSER PREIS DER STEIERMARK...,2020-07-12,Styrian Grand Prix,conventional,Practice 1,2020-07-10 11:00:00+02:00,2020-07-10 09:00:00,...,Practice 3,2020-07-11 12:00:00+02:00,2020-07-11 10:00:00,Qualifying,2020-07-11 15:00:00+02:00,2020-07-11 13:00:00,Race,2020-07-12 15:10:00+02:00,2020-07-12 13:10:00,True
4,3,Hungary,Budapest,FORMULA 1 ARAMCO MAGYAR NAGYDÍJ 2020,2020-07-19,Hungarian Grand Prix,conventional,Practice 1,2020-07-17 11:00:00+02:00,2020-07-17 09:00:00,...,Practice 3,2020-07-18 12:00:00+02:00,2020-07-18 10:00:00,Qualifying,2020-07-18 15:00:00+02:00,2020-07-18 13:00:00,Race,2020-07-19 15:10:00+02:00,2020-07-19 13:10:00,True
5,4,Great Britain,Silverstone,FORMULA 1 PIRELLI BRITISH GRAND PRIX 2020,2020-08-02,British Grand Prix,conventional,Practice 1,2020-07-31 11:00:00+01:00,2020-07-31 10:00:00,...,Practice 3,2020-08-01 11:00:00+01:00,2020-08-01 10:00:00,Qualifying,2020-08-01 14:00:00+01:00,2020-08-01 13:00:00,Race,2020-08-02 14:10:00+01:00,2020-08-02 13:10:00,True
6,5,Great Britain,Silverstone,EMIRATES FORMULA 1 70TH ANNIVERSARY GRAND PRIX...,2020-08-09,70th Anniversary Grand Prix,conventional,Practice 1,2020-08-07 11:00:00+01:00,2020-08-07 10:00:00,...,Practice 3,2020-08-08 11:00:00+01:00,2020-08-08 10:00:00,Qualifying,2020-08-08 14:00:00+01:00,2020-08-08 13:00:00,Race,2020-08-09 14:10:00+01:00,2020-08-09 13:10:00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,17,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2024-09-15,Azerbaijan Grand Prix,conventional,Practice 1,2024-09-13 13:30:00+04:00,2024-09-13 09:30:00,...,Practice 3,2024-09-14 12:30:00+04:00,2024-09-14 08:30:00,Qualifying,2024-09-14 16:00:00+04:00,2024-09-14 12:00:00,Race,2024-09-15 15:00:00+04:00,2024-09-15 11:00:00,True
18,18,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2024-09-22,Singapore Grand Prix,conventional,Practice 1,2024-09-20 17:30:00+08:00,2024-09-20 09:30:00,...,Practice 3,2024-09-21 17:30:00+08:00,2024-09-21 09:30:00,Qualifying,2024-09-21 21:00:00+08:00,2024-09-21 13:00:00,Race,2024-09-22 20:00:00+08:00,2024-09-22 12:00:00,True
20,20,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2024,2024-10-27,Mexico City Grand Prix,conventional,Practice 1,2024-10-25 12:30:00-06:00,2024-10-25 18:30:00,...,Practice 3,2024-10-26 11:30:00-06:00,2024-10-26 17:30:00,Qualifying,2024-10-26 15:00:00-06:00,2024-10-26 21:00:00,Race,2024-10-27 14:00:00-06:00,2024-10-27 20:00:00,True
22,22,United States,Las Vegas,FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX...,2024-11-23,Las Vegas Grand Prix,conventional,Practice 1,2024-11-21 18:30:00-08:00,2024-11-22 02:30:00,...,Practice 3,2024-11-22 18:30:00-08:00,2024-11-23 02:30:00,Qualifying,2024-11-22 22:00:00-08:00,2024-11-23 06:00:00,Race,2024-11-23 22:00:00-08:00,2024-11-24 06:00:00,True
24,24,United Arab Emirates,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2024-12-08,Abu Dhabi Grand Prix,conventional,Practice 1,2024-12-06 13:30:00+04:00,2024-12-06 09:30:00,...,Practice 3,2024-12-07 14:30:00+04:00,2024-12-07 10:30:00,Qualifying,2024-12-07 18:00:00+04:00,2024-12-07 14:00:00,Race,2024-12-08 17:00:00+04:00,2024-12-08 13:00:00,True

In [5]:
all_race_results = []
all_quali_results = []
for _, race in races.iterrows():
  gp_name = race['EventName']
  rnd = int(race['RoundNumber'])

  try:
    race_session = fastf1.get_session(year, rnd, 'R')
    race_session.load()

    race_results = race_session.results[['DriverNumber','Abbreviation','TeamName','Position','Points']]
    race_results['Year'] = race['EventDate'].year
    race_results['GrandPrix'] = gp_name
    race_results['Round'] = rnd

    all_race_results.append(race_results)
  except Exception as e:
      print(f'Unable to Fetch {gp_name} ({year}): {e}')


  try:
     q_session = fastf1.get_session(year, rnd, 'Q')
     q_session.load()
     q_results = q_session.results[['DriverNumber', 'Abbreviation','Position','Q1','Q2','Q3']]
     q_results['Year'] = race['EventDate'].year
     q_results['Round'] = rnd
     q_results['GrandPrix'] = gp_name

     all_quali_results.append(q_results)
  except Exception as e:
      print(f'Unable to Fetch Qualifying for {gp_name} ({year}): {e}')

race_df = pd.concat(all_race_results, ignore_index=True) if all_race_results else pd.DataFrame()
quali_df = pd.concat(all_quali_results, ignore_index=True) if all_quali_results else pd.DataFrame()

race_df.rename(columns={'Abbreviation': 'Driver'}, inplace=True)
quali_df.rename(columns={'Abbreviation': 'Driver'}, inplace=True)

df = pd.merge(
    race_df,
    quali_df[['Year', 'Round', 'GrandPrix', 'Driver', 'Position']].rename(columns={'Position': 'QualPosition'}),
    on=['Year', 'Round', 'GrandPrix', 'Driver'],
    how='left'
)

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['GrandPrix'] = gp_name
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Round'] = rnd
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '11', '14', '4', '81', '44', '27', '22', '18', '23', '3', '20', '77', '24', '2', '31', '10']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Round'] = rnd
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['GrandPrix'] = gp_name
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['GrandPrix'] = gp_name
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Round'] = rnd
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '14', '81', '4', '63', '44', '22', '18', '38', '23', '20', '3', '27', '77', '31', '10', '2', '24']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Round'] = rnd
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['GrandPrix'] = gp_name
core           INFO 	Loading data for Australian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['GrandPrix'] = gp_name
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Round'] = rnd
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['1', '55', '11', '4', '16', '81', '63', '22', '18', '14', '44', '23', '77', '20', '31', '27', '10', '3', '24']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Round'] = rnd
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['GrandPrix'] = gp_name
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['GrandPrix'] = gp_name
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Round'] = rnd
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '55', '14', '81', '44', '16', '63', '22', '3', '27', '77', '23', '31', '18', '10', '20', '2', '24']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['Round'] = rnd
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_results['GrandPrix'] = gp_name
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Year'] = race['EventDate'].year
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['GrandPrix'] = gp_name
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_results['Round'] = rnd
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '4', '81', '16', '55', '63', '27', '77', '18', '3', '31', '23', '10', '24', '20', '44', '22', '2']
C:\Users\ashar\AppData\Local\Temp\ipykernel_11684\3318984264.py:25: SettingWithCopyWarning:

In [6]:
df['Position'] = df['Position'].astype(int)
df['Points'] = df['Points'].astype(int)
df['QualPosition'] = df['QualPosition'].astype(int)

In [7]:
df['Driver_AvgFinish_Season'] = df.groupby(['Year', 'Driver'])['Position'].transform('mean') #checking driver performance over the season
df['Team_AvgPoints_Season'] = df.groupby(['Year', 'TeamName'])['Points'].transform('mean') #checking team performance over the season
df['PrevRaceFinish'] = df.groupby('Driver')['Position'].shift(1).fillna(10)  #checking drivers short term past peprformance
df['Form_Last3'] = df.groupby('Driver')['Position'].transform(lambda x: x.rolling(3, min_periods=1).mean()) #to check driver form for the last 3 races
df

,DriverNumber,Driver,TeamName,Position,Points,Year,GrandPrix,Round,QualPosition,Driver_AvgFinish_Season,Team_AvgPoints_Season,PrevRaceFinish,Form_Last3
0,1,VER,Red Bull Racing,1,26,2020,Austrian Grand Prix,1,1,3.705882,12.323529,10.0,1.000000
1,11,PER,Red Bull Racing,2,18,2020,Austrian Grand Prix,1,5,8.176471,12.323529,10.0,2.000000
2,55,SAI,Ferrari,3,15,2020,Austrian Grand Prix,1,4,5.875000,11.735294,10.0,3.000000
3,16,LEC,Ferrari,4,12,2020,Austrian Grand Prix,1,2,5.058824,11.735294,10.0,4.000000
4,63,RUS,Mercedes,5,10,2020,Austrian Grand Prix,1,3,7.823529,8.617647,10.0,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,20,MAG,Haas F1 Team,16,0,2024,Abu Dhabi Grand Prix,24,15,13.588235,0.888889,12.0,11.666667
1771,30,LAW,RB,17,0,2024,Abu Dhabi Grand Prix,24,12,16.333333,0.611111,16.0,16.333333
1772,77,BOT,Kick Sauber,18,0,2024,Abu Dhabi Grand Prix,24,9,15.944444,0.000000,18.0,16.666667
1773,43,COL,Williams,19,0,2024,Abu Dhabi Grand Prix,24,19,12.666667,0.457143,14.0,15.000000
1774,11,PER,Red Bull Racing,20,0,2024,Abu Dhabi Grand Prix,24,10,10.111111,10.527778,10.0,15.666667

In [9]:
# Average driver finishing position at specific GP (past years only)
df['AvgFinish_AtGP_PastYears'] = (
    df.groupby(['Driver', 'GrandPrix'])['Position'].transform(lambda x: x.shift().expanding().mean()))

# Average qualifying position at this GP (past years only)
df['AvgQual_AtGP_PastYears'] = (
    df.groupby(['Driver', 'GrandPrix'])['QualPosition'].transform(lambda x: x.shift().expanding().mean()))

In [10]:
#scaling [0,1]
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled = scaler.fit_transform(df[['Form_Last3', 'AvgFinish_AtGP_PastYears', 'AvgQual_AtGP_PastYears']].fillna(0))
df[['norm_Form_Last3', 'norm_AvgFinishAtGP', 'norm_AvgQualAtGP']]  = scaled

In [11]:
#since lower finishing position is better in F1
df['norm_AvgFinishAtGP'] = 1 - df['norm_AvgFinishAtGP']  
df['norm_Form_Last3'] = 1 - df['norm_Form_Last3']
df['norm_AvgQualAtGP'] = 1 - df['norm_AvgQualAtGP']
df

,DriverNumber,Driver,TeamName,Position,Points,Year,GrandPrix,Round,QualPosition,Driver_AvgFinish_Season,Team_AvgPoints_Season,PrevRaceFinish,Form_Last3,AvgFinish_AtGP_PastYears,AvgQual_AtGP_PastYears,norm_Form_Last3,norm_AvgFinishAtGP,norm_AvgQualAtGP
0,1,VER,Red Bull Racing,1,26,2020,Austrian Grand Prix,1,1,3.705882,12.323529,10.0,1.000000,NaN,NaN,1.000000,1.0000,1.0000
1,11,PER,Red Bull Racing,2,18,2020,Austrian Grand Prix,1,5,8.176471,12.323529,10.0,2.000000,NaN,NaN,0.947368,1.0000,1.0000
2,55,SAI,Ferrari,3,15,2020,Austrian Grand Prix,1,4,5.875000,11.735294,10.0,3.000000,NaN,NaN,0.894737,1.0000,1.0000
3,16,LEC,Ferrari,4,12,2020,Austrian Grand Prix,1,2,5.058824,11.735294,10.0,4.000000,NaN,NaN,0.842105,1.0000,1.0000
4,63,RUS,Mercedes,5,10,2020,Austrian Grand Prix,1,3,7.823529,8.617647,10.0,5.000000,NaN,NaN,0.789474,1.0000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,20,MAG,Haas F1 Team,16,0,2024,Abu Dhabi Grand Prix,24,15,13.588235,0.888889,12.0,11.666667,12.00,12.00,0.438596,0.4000,0.4000
1771,30,LAW,RB,17,0,2024,Abu Dhabi Grand Prix,24,12,16.333333,0.611111,16.0,16.333333,16.00,15.00,0.192982,0.2000,0.2500
1772,77,BOT,Kick Sauber,18,0,2024,Abu Dhabi Grand Prix,24,9,15.944444,0.000000,18.0,16.666667,17.50,18.50,0.175439,0.1250,0.0750
1773,43,COL,Williams,19,0,2024,Abu Dhabi Grand Prix,24,19,12.666667,0.457143,14.0,15.000000,12.50,12.75,0.263158,0.3750,0.3625
1774,11,PER,Red Bull Racing,20,0,2024,Abu Dhabi Grand Prix,24,10,10.111111,10.527778,10.0,15.666667,11.75,13.00,0.228070,0.4125,0.3500

In [12]:
df['Drivers_Confidence'] = (
    0.4 * df['norm_Form_Last3'] +   #recent form matters most
    0.3 * df['norm_AvgFinishAtGP'] +
    0.3 * df['norm_AvgQualAtGP']
)
#(0.4+0.3+0.3=1) this is the weight of the factors considered

In [13]:
# encoding categorical features
from sklearn.preprocessing import LabelEncoder

encoder_driver = LabelEncoder()
encoder_team = LabelEncoder()
encoder_gp = LabelEncoder()

df['DriverID'] = encoder_driver.fit_transform(df['Driver'])
df['TeamID'] = encoder_team.fit_transform(df['TeamName'])
df['GP_ID'] = encoder_gp.fit_transform(df['GrandPrix'])

In [14]:
df.head()

,DriverNumber,Driver,TeamName,Position,Points,Year,GrandPrix,Round,QualPosition,Driver_AvgFinish_Season,...,Form_Last3,AvgFinish_AtGP_PastYears,AvgQual_AtGP_PastYears,norm_Form_Last3,norm_AvgFinishAtGP,norm_AvgQualAtGP,Drivers_Confidence,DriverID,TeamID,GP_ID
0,1,VER,Red Bull Racing,1,26,2020,Austrian Grand Prix,1,1,3.705882,...,1.0,NaN,NaN,1.000000,1.0,1.0,1.000000,22,8,3
1,11,PER,Red Bull Racing,2,18,2020,Austrian Grand Prix,1,5,8.176471,...,2.0,NaN,NaN,0.947368,1.0,1.0,0.978947,14,8,3
2,55,SAI,Ferrari,3,15,2020,Austrian Grand Prix,1,4,5.875000,...,3.0,NaN,NaN,0.894737,1.0,1.0,0.957895,18,2,3
3,16,LEC,Ferrari,4,12,2020,Austrian Grand Prix,1,2,5.058824,...,4.0,NaN,NaN,0.842105,1.0,1.0,0.936842,10,2,3
4,63,RUS,Mercedes,5,10,2020,Austrian Grand Prix,1,3,7.823529,...,5.0,NaN,NaN,0.789474,1.0,1.0,0.915789,17,6,3

In [15]:
df.to_csv('Cleaned_F1_Data.csv', index=False)